import '@/assets/styles/global.scss'
import Footer from '@/components/layout/footer/Footer'
import Header from '@/components/layout/header/Header'
import Scripts from '@/components/layout/scripts/Scripts'
import Cookies from '@/components/templates/cookies/Cookies'
import SuspenseLoader from '@/components/ui/common/suspense-loader/SuspenseLoader'
import Provider from '@/providers/Provider'
import { Cookie } from '@/shared/enums/cookie/cookie.enum'
import type { Metadata } from 'next'
import { Alumni_Sans, Montserrat } from 'next/font/google'
import { cookies as NextCookies } from 'next/headers'
import type { PropsWithChildren } from 'react'

const alumni = Alumni_Sans({
	weight: ['600', '700', '800'],
	display: 'swap',
	subsets: ['latin'],
	variable: '--font-alumni',
})

const montserrat = Montserrat({
	weight: ['400', '500', '600', '700'],
	display: 'swap',
	subsets: ['latin'],
	variable: '--font-montserrat',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: PropsWithChildren) {
	const cookies = await NextCookies()

	return (
		<html lang="ru">
			<body id="body" className={`${alumni.variable} ${montserrat.variable}`}>
				<link
					rel="stylesheet"
					href="https://cdn.direct.i-dgtl.ru/VerifyWidget.css"
				/>
				<Provider isAuthenticated={cookies.has(Cookie.REFRESH_TOKEN)}>
					<Header />
					<main>{children}</main>
					<Footer />
					<Cookies />
				</Provider>
				<SuspenseLoader />
				<Scripts />
			</body>
		</html>
	)
}
